# Atividade Prática: Análise de Dados no Varejo com NumPy


In [1]:
import numpy as np

## Nível 1: Básico — Faturamento Semanal e Filtros

### Passo 1: Array de peças vendidas na semana


In [2]:
pecas_vendidas = np.array([150, 120, 90, 210, 300, 250, 180])
pecas_vendidas

array([150, 120,  90, 210, 300, 250, 180])

### Passo 2: Estimativa de faturamento (operação vetorizada)

A multiplicação por 50 é aplicada a todos os elementos de uma vez, sem laço `for`.


In [3]:
PRECO_MEDIO = 50

faturamento = pecas_vendidas * PRECO_MEDIO
print('Faturamento diário (R$):', faturamento)
print('Faturamento semanal (R$):', faturamento.sum())

Faturamento diário (R$): [ 7500  6000  4500 10500 15000 12500  9000]
Faturamento semanal (R$): 65000


### Passo 3: Dias de pico (máscara booleana)


In [4]:
mascara_pico = pecas_vendidas > 200
print('Máscara:', mascara_pico)
print('Vendas nos dias de pico:', pecas_vendidas[mascara_pico])
print('Dias de pico (1 = primeiro dia):', np.flatnonzero(mascara_pico) + 1)

Máscara: [False False False  True  True  True False]
Vendas nos dias de pico: [210 300 250]
Dias de pico (1 = primeiro dia): [4 5 6]


## Nível 2: Intermediário — Múltiplas Filiais e Falhas de Sistema

### Passo 1: Matriz 2D (lojas nas linhas, dias nas colunas)


In [5]:
lojas = np.array(['Loja A', 'Loja B', 'Loja C'])

vendas_filiais = np.array([
    [200, 220, np.nan, 250],
    [150, 180, 160, 190],
    [300, 310, 290, 330],
])
print(vendas_filiais)
print('Shape:', vendas_filiais.shape)

[[200. 220.  nan 250.]
 [150. 180. 160. 190.]
 [300. 310. 290. 330.]]
Shape: (3, 4)


### Passo 2: Total por loja (`axis=1`)

A soma comum propaga o `nan` da Loja A. Para comparação, `np.nansum` ignora a lacuna.


In [6]:
total_por_loja = np.sum(vendas_filiais, axis=1)
total_por_loja_sem_nan = np.nansum(vendas_filiais, axis=1)

for loja, total, total_limpo in zip(lojas, total_por_loja, total_por_loja_sem_nan):
    print(f'{loja}: np.sum = {total} | np.nansum = {total_limpo}')

Loja A: np.sum = nan | np.nansum = 670.0
Loja B: np.sum = 680.0 | np.nansum = 680.0
Loja C: np.sum = 1230.0 | np.nansum = 1230.0


### Passo 3: Média diária geral da rede (ignorando `nan`)


In [7]:
media_contaminada = np.mean(vendas_filiais)
media_geral = np.nanmean(vendas_filiais)

print('np.mean (contaminada):', media_contaminada)
print(f'np.nanmean (correta): {media_geral:.2f} peças por loja/dia')

np.mean (contaminada): nan
np.nanmean (correta): 234.55 peças por loja/dia


### Passo 4: Meta diária de 200 peças com `np.where()`

Obs.: como `nan >= 200` é `False`, o dia com falha de sistema da Loja A aparece como `'Abaixo'`.


In [8]:
META_DIARIA = 200

status_meta = np.where(vendas_filiais >= META_DIARIA, 'Meta Atingida', 'Abaixo')
print(status_meta)

[['Meta Atingida' 'Meta Atingida' 'Abaixo' 'Meta Atingida']
 ['Abaixo' 'Abaixo' 'Abaixo' 'Abaixo']
 ['Meta Atingida' 'Meta Atingida' 'Meta Atingida' 'Meta Atingida']]


## Nível 3: Avançado — Categorização e Destaques de Marketing

### Passo 1: Amostra de 50 vendas com semente fixa


In [9]:
rng = np.random.default_rng(42)

departamentos = ['Eletrônicos', 'Roupas', 'Casa']
amostra_vendas = rng.choice(departamentos, size=50)
amostra_vendas[:10]

array(['Eletrônicos', 'Casa', 'Roupas', 'Roupas', 'Roupas', 'Casa',
       'Eletrônicos', 'Casa', 'Eletrônicos', 'Eletrônicos'], dtype='<U11')

### Passo 2: Volume de vendas por departamento (`np.unique`)


In [10]:
categorias, contagens = np.unique(amostra_vendas, return_counts=True)

for categoria, contagem in zip(categorias, contagens):
    print(f'{categoria}: {contagem} vendas')
print('Total:', contagens.sum())

Casa: 21 vendas
Eletrônicos: 12 vendas
Roupas: 17 vendas
Total: 50


### Passo 3: Campanha campeã (`argmax`)


In [11]:
faturamento_campanhas = np.array([12000, 45000, 23000, 89000, 31000])

indice_campea = faturamento_campanhas.argmax()
print(f'Índice da campanha campeã: {indice_campea}')
print(f'Campanha {indice_campea + 1} faturou R$ {faturamento_campanhas[indice_campea]:,}')

Índice da campanha campeã: 3
Campanha 4 faturou R$ 89,000


# Atividade Prática: Organização e Transformação de Dados com NumPy


## Nível 1: Básico — Geração de Sequências e Tipagem de Dados

### Passo 1: Dias do mês com `np.arange`


In [12]:
dias_mes = np.arange(1, 31)
dias_mes

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

### Passo 2: Metas igualmente espaçadas com `np.linspace`


In [13]:
metas_semana = np.linspace(20000, 30000, 5)
metas_semana

array([20000., 22500., 25000., 27500., 30000.])

### Passo 3: Conversão do estoque para inteiros (`.astype(int)`)

O `astype(int)` trunca a parte decimal (não arredonda): `30.9` vira `30`.


In [14]:
estoque_fisico = np.array([10.5, 20.1, 30.9])
estoque_inteiro = estoque_fisico.astype(int)

print(estoque_fisico, estoque_fisico.dtype)
print(estoque_inteiro, estoque_inteiro.dtype)

[10.5 20.1 30.9] float64
[10 20 30] int64


### Passo 4: Últimos 5 dias, do mais recente para o mais antigo


In [15]:
ultimos_5_dias = dias_mes[-5:][::-1]
ultimos_5_dias

array([30, 29, 28, 27, 26])

## Nível 2: Intermediário — Redimensionamento e Proteção de Dados

### Passo 1: 12 meses de visitas em 4 trimestres (`.reshape(4, 3)`)


In [16]:
visitas_mensais = np.array([
    1200, 1350, 1100, 1500, 1620, 1580,
    1700, 1750, 1680, 1900, 2100, 2400,
])

visitas_trimestrais = visitas_mensais.reshape(4, 3)
print(visitas_trimestrais)
print('Shape:', visitas_trimestrais.shape)

[[1200 1350 1100]
 [1500 1620 1580]
 [1700 1750 1680]
 [1900 2100 2400]]
Shape: (4, 3)


### Passo 2: Empilhando os semestres com `np.vstack()`

Cada semestre tem 2 trimestres × 3 meses.


In [17]:
semestre_1_marketing = np.array([
    [1200, 1350, 1100],
    [1500, 1620, 1580],
])
semestre_2_comercial = np.array([
    [1700, 1750, 1680],
    [1900, 2100, 2400],
])

visitas_ano = np.vstack((semestre_1_marketing, semestre_2_comercial))
print(visitas_ano)
print('Shape:', visitas_ano.shape)

[[1200 1350 1100]
 [1500 1620 1580]
 [1700 1750 1680]
 [1900 2100 2400]]
Shape: (4, 3)


### Passo 3: Projeção do 1º trimestre com `.copy()`

Sem `.copy()`, a fatia é uma _view_: alterar a fatia altera também o array original.


In [18]:
# A "pegadinha": a view compartilha memória com o original
teste_view = visitas_ano.copy()
fatia_view = teste_view[0]
fatia_view[0] = 0
print('Original alterado pela view:', teste_view[0])

# Forma segura: cópia independente
projecao_t1 = visitas_ano[0].copy()
projecao_t1 = (projecao_t1 * 1.10).astype(int)  # cenário de +10%

print('Projeção 1º trimestre:', projecao_t1)
print('Original intacto:     ', visitas_ano[0])

Original alterado pela view: [   0 1350 1100]
Projeção 1º trimestre: [1320 1485 1210]
Original intacto:      [1200 1350 1100]


### Passo 4: Achatando a matriz com `ravel()`


In [19]:
relatorio_corrido = visitas_ano.ravel()
print(relatorio_corrido)
print('Shape:', relatorio_corrido.shape)

[1200 1350 1100 1500 1620 1580 1700 1750 1680 1900 2100 2400]
Shape: (12,)


## Nível 3: Avançado — Ranking, Broadcasting e Resolução de Sistemas

### Passo 1: Ranking de alunos com `np.argsort()`


In [20]:
notas = np.array([85, 92, 78, 95, 88])

indices_crescente = np.argsort(notas)
indices_ranking = indices_crescente[::-1]  # da maior para a menor nota
print('argsort (crescente):', indices_crescente)
print('Ranking (índices dos alunos):', indices_ranking)

posicao_no_ranking = np.empty_like(indices_ranking)
posicao_no_ranking[indices_ranking] = np.arange(1, len(notas) + 1)

for aluno, (nota, posicao) in enumerate(zip(notas, posicao_no_ranking), start=1):
    print(f'Aluno {aluno}: nota {nota} -> {posicao}º lugar')

argsort (crescente): [2 0 4 1 3]
Ranking (índices dos alunos): [3 1 4 0 2]
Aluno 1: nota 85 -> 4º lugar
Aluno 2: nota 92 -> 2º lugar
Aluno 3: nota 78 -> 5º lugar
Aluno 4: nota 95 -> 1º lugar
Aluno 5: nota 88 -> 3º lugar


### Passo 2: Broadcasting de descontos com `np.newaxis`

Preços em coluna `(3, 1)` × descontos em linha `(3,)` resultam numa tabela `(3, 3)`: cada linha é um produto e cada coluna um percentual de desconto.


In [21]:
precos_base = np.array([100, 250, 400])
descontos = np.array([0.05, 0.10, 0.20])

precos_coluna = precos_base[:, np.newaxis]
print('Shape linha:', precos_base.shape, '| Shape coluna:', precos_coluna.shape)

precos_com_desconto = precos_coluna * (1 - descontos)
print(precos_com_desconto)

Shape linha: (3,) | Shape coluna: (3, 1)
[[ 95.   90.   80. ]
 [237.5 225.  200. ]
 [380.  360.  320. ]]


### Passo 3: Custo unitário com `np.linalg.solve()`

- Projeto A: `2·placa + 1·sensor = 500`
- Projeto B: `1·placa − 1·sensor = 100` (sensor devolvido/estornado)


In [22]:
A = np.array([
    [2, 1],
    [1, -1],
])
b = np.array([500, 100])

placa, sensor = np.linalg.solve(A, b)
print(f'Placa robótica: R$ {placa:.2f}')
print(f'Sensor: R$ {sensor:.2f}')
print('Verificação A @ x == b:', np.allclose(A @ np.array([placa, sensor]), b))

Placa robótica: R$ 200.00
Sensor: R$ 100.00
Verificação A @ x == b: True
